[connections.snowflake]
account = "MPIAENE-EW69056"
user = "ashokdorle83"
password = "xxx"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
